global:
  postgresql:
    auth:
      database: vauhtijuoksu-api
      postgresPassword: topsecret
#image:
  # Upgrade version for pull command in deployment/build.gradle.kts when upgrading this
  #repository: postgres
  #tag: 16.3
