apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mockserver.fullname" . }}
  labels:
    {{- include "mockserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mockserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mockserver.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/openapi-cm.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 50m
          env:
            - name: OPENAPI_MOCK_SPECIFICATION_URL
              value: "/apidoc/openapi.yaml"
            - name: OPENAPI_MOCK_USE_EXAMPLES
              value: {{ .Values.use_examples }}
            - name: OPENAPI_MOCK_CORS_ENABLED
              value: "1"
          volumeMounts:
            - name: apidoc
              mountPath: /apidoc
              readOnly: true
      volumes:
        - name: apidoc
          configMap:
            name: {{ include "mockserver.fullname" . }}-openapi-spec
