apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mockserver.fullname" . }}
  labels:
    {{- include "mockserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mockserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mockserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 50m
          env:
            - name: OPENAPI_MOCK_SPECIFICATION_URL
              value: {{ .Values.specification_url }}
            - name: OPENAPI_MOCK_USE_EXAMPLES
              value: {{ .Values.use_examples }}
