apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mockserver.fullname" . }}
  labels:
    {{- include "mockserver.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.host }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mockserver
                port:
                  number: 80
