apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mockserver.fullname" . }}
  labels:
    {{- include "mockserver.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - dev.vauhtijuoksu.fi
      secretName: tls-secret
  rules:
    - host: dev.vauhtijuoksu.fi
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: mockserver
                port:
                  number: 80
