apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vauhtijuoksu-api.fullname" . }}-conf
  labels:
    {{- include "vauhtijuoksu-api.labels" . | nindent 4 }}
data:
  conf.yaml: |
    server:
      port: 8080
      htpasswdFileLocation: /htpasswd/htpasswd
      corsHeader: {{ .Values.server.corsHeader }}
    database:
      database: {{ .Values.database.database }}
      address: {{ .Values.database.address }}
      port: {{ .Values.database.port }}
      user: {{ .Values.database.user }}
      poolSize: {{ .Values.database.poolSize }}
    oAuth:
      secret: {{ .Values.oAuth.secret }}
      callbackUrl: {{ .Values.oAuth.callbackUrl }}
      baseAuthorizationUrl: {{ .Values.oAuth.baseAuthorizationUrl }}
      authorizationPath: {{ .Values.oAuth.authorizationPath }}
      tokenPath: {{ .Values.oAuth.tokenPath }}
      tokenRevocationUrl: {{ .Values.oAuth.tokenRevocationUrl }}
    discordClient:
      vauhtijuoksuServerId: {{ .Values.discord.vauhtijuoksuServerId }}
      adminRoleId: {{ .Values.discord.adminRoleId }}
    redis:
      host: {{ .Values.redis.host }}
