apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vauhtijuoksu-api.fullname" . }}-conf
  labels:
    {{- include "vauhtijuoksu-api.labels" . | nindent 4 }}
data:
  conf.yaml: |
    server:
      port: 8080
      htpasswdFileLocation: /configuration/htpasswd
      corsHeader: {{ .Values.server.corsHeader }}
    database:
      database: {{ .Values.database.database }}
      address: {{ .Values.database.address }}
      port: {{ .Values.database.port }}
      user: {{ .Values.database.user }}
      poolSize: {{ .Values.database.poolSize }}
