apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vauhtijuoksu-api.fullname" . }}
  labels:
    {{- include "vauhtijuoksu-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vauhtijuoksu-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vauhtijuoksu-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "vauhtijuoksu.azurecr.io/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 50m
          volumeMounts:
            - name: configuration
              mountPath: /configuration
      volumes:
        - name: configuration
          configMap:
            name: vauhtijuoksu-api
