apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vauhtijuoksu-api.fullname" . }}
  labels:
    {{- include "vauhtijuoksu-api.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "vauhtijuoksu-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vauhtijuoksu-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
          volumeMounts:
          - name: configuration
            mountPath: /configuration
            readOnly: true
      volumes:
      - name: configuration
        projected:
          sources:
          - configMap:
              name: '{{ include "vauhtijuoksu-api.fullname" . }}-conf'
          - configMap:
              name: '{{ include "vauhtijuoksu-api.fullname" . }}-log4j2'
