apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vauhtijuoksu-api.fullname" . }}
  labels:
    {{- include "vauhtijuoksu-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vauhtijuoksu-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vauhtijuoksu-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /gamedata
              port: http
          volumeMounts:
            - name: configuration
              mountPath: /configuration
              readOnly: true
            - name: logging
              mountPath: /logging
              readOnly: true
            - name: htpasswd
              mountPath: /htpasswd
              readOnly: true
          envFrom:
            - secretRef:
                name: {{ .Values.redis.secret }}
      volumes:
        - name: configuration
          projected:
            sources:
              - configMap:
                  name: '{{ include "vauhtijuoksu-api.fullname" . }}-conf'
              - secret:
                  name: '{{ .Values.database.secret }}'
              - secret:
                  name: '{{ .Values.oAuth.secret }}'
        - name: logging
          configMap:
            name: '{{ include "vauhtijuoksu-api.fullname" . }}-log4j2'
        - name: htpasswd
          secret:
            secretName: '{{ .Values.server.htpasswdSecret }}'
