apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vauhtijuoksu-api.fullname" . }}-log4j2
  labels:
    {{- include "vauhtijuoksu-api.labels" . | nindent 4 }}
data:
  log4j2.yaml: |
    Configuration:
      status: info
      monitorInterval: 15
      name: Vauhtijuoksu logger
      appenders:
        Console:
          name: STDOUT
          target: SYSTEM_OUT
          PatternLayout:
            Pattern: "%d{hh:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

      Loggers:
        Root:
          level: {{ .Values.logging.level }}
          AppenderRef:
            ref: STDOUT
