name: Publish mockserver

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: vauhtijuoksu
          resource-group: Vauhtijuoksu-Azure-Sponsorship
      - uses: azure/setup-helm@v1
        id: install
      - name: Deploy mock server to AKS
        run: |
          helm upgrade --install mockserver deployment/mockserver
