name: Try TS

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v3.2.3
      with:
        oauth-client-id: "${{ secrets.TS_OAUTH_CLIENT_ID }}"
        oauth-secret: "${{ secrets.TS_OAUTH_SECRET }}"
        tags: 'tag:gh-runner'
        use-cache: 'true'
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v4
    - name: Setup kubeconfig
      run: |
        mkdir ~/.kube
        echo "${{ vars.KUBECONFIG }}" > ~/.kube/config
        kubectl get all
